# Generated by Django 5.2.7 on 2025-10-19 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления:')),
                ('name', models.CharField(help_text='Укажите название звена сети', max_length=255, verbose_name='Название звена сети:')),
                ('email', models.EmailField(blank=True, help_text='Укажите email контактного лица/офиса', max_length=254, null=True, verbose_name='Email:')),
                ('country', models.CharField(blank=True, help_text='Укажите страну', max_length=100, null=True, verbose_name='Страна:')),
                ('city', models.CharField(blank=True, help_text='Укажите город', max_length=100, null=True, verbose_name='Город:')),
                ('street', models.CharField(blank=True, help_text='Укажите улицу', max_length=100, null=True, verbose_name='Улица:')),
                ('house_number', models.CharField(blank=True, help_text='Укажите номер дома', max_length=20, null=True, verbose_name='Дом:')),
                ('debt_to_supplier', models.DecimalField(decimal_places=2, default=0.0, help_text='Укажите задолженность перед поставщиком', max_digits=10, verbose_name='Задолженность перед поставщиком:')),
                ('parent', models.ForeignKey(blank=True, help_text='Укажите поставщика (предыдущий по иерархии объект сети)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='network.networknode', verbose_name='Поставщик:')),
                ('product', models.ForeignKey(blank=True, help_text='Укажите продукт', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_nodes', to='products.product', verbose_name='Продукт:')),
            ],
            options={
                'verbose_name': 'Звено сети',
                'verbose_name_plural': 'Звенья сети',
                'ordering': ['name'],
            },
        ),
    ]
