# Generated by Django 5.2.7 on 2025-10-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networknode',
            name='level',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Уровень иерархии:'),
        ),
    ]
