# Generated by Django 5.2.7 on 2025-10-20 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_networknode_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления:')),
                ('country', models.CharField(blank=True, help_text='Укажите страну', max_length=100, null=True, verbose_name='Страна:')),
                ('city', models.CharField(blank=True, help_text='Укажите город', max_length=100, null=True, verbose_name='Город:')),
                ('street', models.CharField(blank=True, help_text='Укажите улицу', max_length=100, null=True, verbose_name='Улица:')),
                ('house_number', models.CharField(blank=True, help_text='Укажите номер дома', max_length=20, null=True, verbose_name='Дом:')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'ordering': ['country', 'city', 'street', 'house_number'],
            },
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='city',
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='country',
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='street',
        ),
        migrations.AddField(
            model_name='networknode',
            name='address',
            field=models.OneToOneField(blank=True, help_text='Укажите адрес', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_node', to='network.addressnode', verbose_name='Адрес:'),
        ),
    ]
