# Generated by Django 5.2.7 on 2025-10-20 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_networknode_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networknode',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Укажите адрес', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node', to='network.addressnode', verbose_name='Адрес:'),
        ),
    ]
